apiVersion: v1
kind: Service
metadata:
  name: {{ include "haystack.fullname" . }}
  labels:
    {{- include "haystack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ui.port }}
      targetPort: ui
      protocol: TCP
      name: ui
  selector:
    {{- include "haystack.selectorLabels" . | nindent 4 }}
